### ISSUE TITLE
OverlayEntry is null in a ListView

### ISSUE THREAD

**Issue by bebaoboy** [maheshj01/searchfield#153]
**Describe the bug**
```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/overlay.dart': Failed assertion: line 207 pos 12: '_overlay != null': is not true.)
```

**To Reproduce**
<details>
<summary>Demo video (app froze)</summary>

https://github.com/user-attachments/assets/37a495e3-d1c1-4113-8c59-a02a0c671bbd

</details>

Steps to reproduce the behavior in the demo video:
1. Clone the main branch.
2. Add more searchfields to the example file.
3. Run the example app like the video below: search on the second field, then scroll back up (the second field is now out of sight), then tap on the first field.

![image](https://github.com/user-attachments/assets/5395f387-8e23-440f-bee4-b0da3a491f2f)

Further investigation, it seems that the Overlay Entry was invalidated by the list view due to being scroll off-screen.
![image](https://github.com/user-attachments/assets/e7e9a53b-6981-42ca-9a25-98504408033b)

[x] By clicking this checkbox, I confirm I am using the latest version of the package found on [pub.dev/searchfield](https://pub.dev/packages/searchfield)

**Code sample**
<details>
<summary>Show code sample</summary>
Well nothing much, I just put two UserSelect() on the same page. Pretty sure they don't conflict when sharing the same sample data.

![image](https://github.com/user-attachments/assets/10261077-050f-4dff-a2a9-f0848dda221c)
</details>

<details>
<summary>Raw code of example main.dart</summary>

``` dart
import 'package:example/custom.dart';
import 'package:example/network_sample.dart';
import 'package:example/pagination.dart';
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: SearchFieldSample(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SearchFieldSample extends StatefulWidget {
  const SearchFieldSample({Key? key}) : super(key: key);

  @override
  State<SearchFieldSample> createState() => _SearchFieldSampleState();
}

class _SearchFieldSampleState extends State<SearchFieldSample> {
  int suggestionsCount = 12;
  final focus = FocusNode();

  @override
  void initState() {
    suggestions = [
      'United States',
      'Germany',
      'Canada',
      'United Kingdom',
      'France',
      'Italy',
      'Spain',
      'Australia',
      'India',
      'China',
      'Japan',
      'Brazil',
      'South Africa',
      'Mexico',
      'Argentina',
      'Russia',
      'Indonesia',
      'Turkey',
      'Saudi Arabia',
      'Nigeria',
      'Egypt',
    ];
    super.initState();
  }

  final TextEditingController searchController = TextEditingController();
  var suggestions = <String>[];
  int counter = 0;
  @override
  Widget build(BuildContext context) {
    Widget searchChild(x) => Padding(
          padding: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 12),
          child: Text(x, style: TextStyle(fontSize: 18, color: Colors.black)),
        );
    return Scaffold(
        appBar: AppBar(title: Text('Searchfield Demo')),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              suggestionsCount++;
              counter++;
              suggestions.add('suggestion $suggestionsCount');
            });
          },
          child: Icon(Icons.add),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListView(
            children: [
              UserSelect(),
              SizedBox(
                height: 550,
              ),
              TextFormField(
                  autovalidateMode: AutovalidateMode.onUserInteraction,
                  decoration: InputDecoration(
                    labelText: 'Flutter TextFormField',
                  ),
                  validator: (value) {
                    if (value == null || value.length < 4) {
                      return 'error';
                    }
                    return null;
                  }),
              SizedBox(
                height: 50,
              ),
              UserSelect(),
              SizedBox(
                height: 50,
              ),
              SearchField(
                hint: 'Basic SearchField',
                initialValue: SearchFieldListItem<String>('ABC'),
                suggestions: ['ABC', 'DEF', 'GHI', 'JKL']
                    .map(SearchFieldListItem<String>.new)
                    .toList(),
                suggestionState: Suggestion.expand,
              ),
              SizedBox(
                height: 50,
              ),
              Pagination(),
              SizedBox(
                height: 50,
              ),
              NetworkSample(),
              SizedBox(
                height: 50,
              ),
              SearchField(
                suggestionDirection: SuggestionDirection.flex,
                onSearchTextChanged: (query) {
                  final filter = suggestions
                      .where((element) =>
                          element.toLowerCase().contains(query.toLowerCase()))
                      .toList();
                  return filter
                      .map((e) =>
                          SearchFieldListItem<String>(e, child: searchChild(e)))
                      .toList();
                },
                initialValue: SearchFieldListItem<String>('United States'),
                controller: searchController,
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null || !suggestions.contains(value.trim())) {
                    return 'Enter a valid country name';
                  }
                  return null;
                },
                onSubmit: (x) {},
                autofocus: false,
                key: const Key('searchfield'),
                hint: 'Search by country name',
                itemHeight: 50,
                onTapOutside: (x) {
                  // focus.unfocus();
                },
                scrollbarDecoration: ScrollbarDecoration(
                  thickness: 12,
                  radius: Radius.circular(6),
                  trackColor: Colors.grey,
                  trackBorderColor: Colors.red,
                  thumbColor: Colors.orange,
                ),
                suggestionStyle:
                    const TextStyle(fontSize: 18, color: Colors.black),
                searchStyle: TextStyle(fontSize: 18, color: Colors.black),
                suggestionItemDecoration: BoxDecoration(
                  // color: Colors.grey[100],
                  // borderRadius: BorderRadius.circular(10),
                  border: Border(
                    bottom: BorderSide(
                      color: Colors.grey.shade200,
                      width: 1,
                    ),
                  ),
                ),
                searchInputDecoration: InputDecoration(
                  hintStyle: TextStyle(fontSize: 18, color: Colors.grey),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.orange,
                      style: BorderStyle.solid,
                    ),
                  ),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.black,
                      style: BorderStyle.solid,
                    ),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 20,
                  ),
                ),
                suggestionsDecoration: SuggestionDecoration(
                    // border: Border.all(color: Colors.orange),
                    elevation: 8.0,
                    selectionColor: Colors.grey.shade100,
                    hoverColor: Colors.purple.shade100,
                    gradient: LinearGradient(
                      colors: [
                        Color(0xfffc466b),
                        Color.fromARGB(255, 103, 128, 255)
                      ],
                      stops: [0.25, 0.75],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.only(
                      bottomLeft: Radius.circular(10),
                      bottomRight: Radius.circular(10),
                    )),
                suggestions: suggestions
                    .map((e) =>
                        SearchFieldListItem<String>(e, child: searchChild(e)))
                    .toList(),
                focusNode: focus,
                suggestionState: Suggestion.expand,
                onSuggestionTap: (SearchFieldListItem<String> x) {},
              ),
              SizedBox(
                height: 50,
              ),
              SearchField(
                enabled: false,
                hint: 'Disabled SearchField',
                suggestions: ['ABC', 'DEF', 'GHI', 'JKL']
                    .map(SearchFieldListItem<String>.new)
                    .toList(),
                suggestionState: Suggestion.expand,
              ),
              SizedBox(
                height: 50,
              ),
              NetworkSample(),
              Text(
                'Counter: $counter',
                style: Theme.of(context).textTheme.bodyLarge,
              ),
            ],
          ),
        ));
  }
}
```

</details>

**Comment by maheshmnj** [comment]
I think will be fixed by handling the onTapOutside properly.

**Comment by maheshmnj** [comment]
I am guessing if this could be related to https://github.com/maheshmnj/searchfield/issues/43

**Comment by maheshj01** [comment]
@bebaoboy please check with v1.2.5

**Comment by maheshj01** [comment]
reproduces on latest version 1.3.1

<details>
<summary>code sample</summary>

```dart
import 'package:example/UserSelect.dart';
import 'package:example/network_sample.dart';
import 'package:example/pagination.dart';
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: SearchFieldSample(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SearchFieldSample extends StatefulWidget {
  const SearchFieldSample({Key? key}) : super(key: key);

  @override
  State<SearchFieldSample> createState() => _SearchFieldSampleState();
}

class _SearchFieldSampleState extends State<SearchFieldSample> {
  int suggestionsCount = 12;
  final focus = FocusNode();

  @override
  void initState() {
    suggestions = [
      'United States',
      'Germany',
      'Canada',
      'United Kingdom',
      'France',
      'Italy',
      'Spain',
      'Australia',
      'India',
      'China',
      'Japan',
      'Brazil',
      'South Africa',
      'Mexico',
      'Argentina',
      'Russia',
      'Indonesia',
      'Turkey',
      'Saudi Arabia',
      'Nigeria',
      'Egypt',
    ];
    super.initState();
  }

  final TextEditingController searchController = TextEditingController();
  var suggestions = <String>[];
  int counter = 0;
  @override
  Widget build(BuildContext context) {
    Widget searchChild(x) => Padding(
          padding: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 12),
          child: Text(x, style: TextStyle(fontSize: 18, color: Colors.black)),
        );
    return Scaffold(
        appBar: AppBar(title: Text('Searchfield Demo')),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              suggestionsCount++;
              counter++;
              suggestions.add('suggestion $suggestionsCount');
            });
          },
          child: Icon(Icons.add),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListView(
            children: [
              UserSelect(),
              SizedBox(
                height: 550,
              ),
              TextFormField(
                  autovalidateMode: AutovalidateMode.onUserInteraction,
                  decoration: InputDecoration(
                    labelText: 'Flutter TextFormField',
                  ),
                  validator: (value) {
                    if (value == null || value.length < 4) {
                      return 'error';
                    }
                    return null;
                  }),
              SizedBox(
                height: 50,
              ),
              UserSelect(),
              SizedBox(
                height: 50,
              ),
              SearchField(
                hint: 'Basic SearchField',
                suggestions: ['ABC', 'DEF', 'GHI', 'JKL']
                    .map(SearchFieldListItem<String>.new)
                    .toList(),
                suggestionState: Suggestion.expand,
              ),
              SizedBox(
                height: 50,
              ),
              Pagination(),
              SizedBox(
                height: 50,
              ),
              NetworkSample(),
              SizedBox(
                height: 50,
              ),
              SearchField(
                suggestionDirection: SuggestionDirection.flex,
                onSearchTextChanged: (query) {
                  final filter = suggestions
                      .where((element) =>
                          element.toLowerCase().contains(query.toLowerCase()))
                      .toList();
                  return filter
                      .map((e) =>
                          SearchFieldListItem<String>(e, child: searchChild(e)))
                      .toList();
                },
                controller: searchController,
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null || !suggestions.contains(value.trim())) {
                    return 'Enter a valid country name';
                  }
                  return null;
                },
                onSubmit: (x) {},
                autofocus: false,
                key: const Key('searchfield'),
                hint: 'Search by country name',
                itemHeight: 50,
                onTapOutside: (x) {
                  // focus.unfocus();
                },
                scrollbarDecoration: ScrollbarDecoration(
                  thickness: 12,
                  radius: Radius.circular(6),
                  trackColor: Colors.grey,
                  trackBorderColor: Colors.red,
                  thumbColor: Colors.orange,
                ),
                suggestionStyle:
                    const TextStyle(fontSize: 18, color: Colors.black),
                suggestionItemDecoration: BoxDecoration(
                  // color: Colors.grey[100],
                  // borderRadius: BorderRadius.circular(10),
                  border: Border(
                    bottom: BorderSide(
                      color: Colors.grey.shade200,
                      width: 1,
                    ),
                  ),
                ),
                searchInputDecoration: SearchInputDecoration(
                  searchStyle: TextStyle(fontSize: 18, color: Colors.black),
                  hintStyle: TextStyle(fontSize: 18, color: Colors.grey),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.orange,
                      style: BorderStyle.solid,
                    ),
                  ),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.black,
                      style: BorderStyle.solid,
                    ),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 20,
                  ),
                ),
                suggestionsDecoration: SuggestionDecoration(
                    // border: Border.all(color: Colors.orange),
                    elevation: 8.0,
                    selectionColor: Colors.grey.shade100,
                    hoverColor: Colors.purple.shade100,
                    gradient: LinearGradient(
                      colors: [
                        Color(0xfffc466b),
                        Color.fromARGB(255, 103, 128, 255)
                      ],
                      stops: [0.25, 0.75],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.only(
                      bottomLeft: Radius.circular(10),
                      bottomRight: Radius.circular(10),
                    )),
                suggestions: suggestions
                    .map((e) =>
                        SearchFieldListItem<String>(e, child: searchChild(e)))
                    .toList(),
                focusNode: focus,
                suggestionState: Suggestion.expand,
                onSuggestionTap: (SearchFieldListItem<String> x) {},
              ),
              SizedBox(
                height: 50,
              ),
              SearchField(
                enabled: false,
                hint: 'Disabled SearchField',
                suggestions: ['ABC', 'DEF', 'GHI', 'JKL']
                    .map(SearchFieldListItem<String>.new)
                    .toList(),
                suggestionState: Suggestion.expand,
              ),
              SizedBox(
                height: 50,
              ),
              NetworkSample(),
              Text(
                'Counter: $counter',
                style: Theme.of(context).textTheme.bodyLarge,
              ),
            ],
          ),
        ));
  }
}

```
</details> 

<details>
<summary>logs</summary>

```console
mahesh@MacBook-Pro-81 example % flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008132-0009284E1E39001C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008132-0009284E1E39001C, name:My Mac }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...                                           
✓ Built build/macos/Build/Products/Debug/example.app
Syncing files to device macOS...                                   145ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:62528/VoCsTaWmbOw=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:62528/VoCsTaWmbOw=/

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _SelectionKeepAlive(state:
_SelectionKeepAliveState#49361):
A FocusNode was used after being disposed.
Once you have called dispose() on a FocusNode, it can no longer be used.

The relevant error-causing widget was:
  ListView
  ListView:file:///Users/mahesh/Development/oss/my_packages/searchfield/example/lib/main.dart:97:18

When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:275:27)
#3      _SearchFieldState.initialize (package:searchfield/src/searchfield.dart:418:19)
#4      _SearchFieldState.initState (package:searchfield/src/searchfield.dart:506:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5860:55)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
...     Normal element mounting (41 frames)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
#49     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1000:37)
#50     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:984:20)
#51     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:19)
#52     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:975:12)
#53     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:372:23)
#54     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2827:17)
#55     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1161:15)
#56     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2826:14)
#57     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:360:5)
#58     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:511:5)
#59     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:242:19)
#60     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:283:12)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#62     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:133:12)
#63     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#65     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:608:13)
#66     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1576:12)
#67     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1467:20)
#68     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2548:7)
#69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1112:18)
#70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1125:15)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:616:23)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1231:13)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:482:5)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1355:9)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1208:5)
#77     _invoke (dart:ui/hooks.dart:316:13)
#78     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:428:5)
#79     _drawFrame (dart:ui/hooks.dart:288:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 277 pos 16: 'child == null ||
indexOf(child) > index': is not true.
Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 277 pos 16: 'child == null ||
indexOf(child) > index': is not true.
Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 277 pos 16: 'child == null ||
indexOf(child) > index': is not true.
Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 277 pos 16: 'child == null ||
indexOf(child) > index': is not true.
Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 277 pos 16: 'child == null ||
indexOf(child) > index': is not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1025 pos 14: '_childElements.containsKey(index)': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 203 pos 12: '!_debugDuringDeviceUpdate': is
not true.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: Null check operator used on a null value
```
</details>

**Comment by maheshj01** [comment]
This was fixed in v1.2.5 here https://github.com/maheshj01/searchfield/pull/209/
